title: Xarpite
description: An interpreted language for one-liners
baseurl: "/xarpite"
url: "https://mirrgieriana.github.io"
docs_base: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Theme
theme: null

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-optional-front-matter

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
