title: Xarpite
description: An interpreted language for one-liners
baseurl: "/xarpite"
url: "https://mirrgieriana.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..3

# Theme
theme: null

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      menu_relative: "../_menu.html"
  - scope:
      path: "docs/ja"
    values:
      toc: true
      menu_relative: "../docs/ja/_menu.html"
  - scope:
      path: "docs/en"
    values:
      toc: true
      lang: en
      menu_relative: "../docs/en/_menu.html"

plugins:
  - jekyll-optional-front-matter

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
